FUNCTION Z_CREATE_QUOTE_{{CUSTOMER}}.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(CUSTOMER_ID) TYPE  KUNNR
*"     VALUE(QUOTE_DATE) TYPE  DATUM DEFAULT SY-DATUM
*"     VALUE(VALID_UNTIL) TYPE  DATUM
*"     VALUE(SALES_ORG) TYPE  VKORG DEFAULT '1000'
*"     VALUE(DIST_CHANNEL) TYPE  VTWEG DEFAULT '10'
*"     VALUE(DIVISION) TYPE  SPART DEFAULT '00'
{{CUSTOM_IMPORTS}}
*"  EXPORTING
*"     VALUE(QUOTE_NUMBER) TYPE  VBELN
*"     VALUE(MESSAGES) TYPE  BAPIRET2_T
*"  EXCEPTIONS
*"      ERROR
*"----------------------------------------------------------------------

*----------------------------------------------------------------------*
* Quote Creation Function Module for {{CUSTOMER}}
* Generated by SAP Endpoint Generator
* Date: {{DATE}}
*
* Purpose: Create sales quote with support for custom fields
* Version: {{SAP_VERSION}}
*----------------------------------------------------------------------*

  " Data declarations
  DATA: lv_quote_number   TYPE vbeln,
        lt_return         TYPE TABLE OF bapiret2,
        ls_return         TYPE bapiret2,
        lv_error          TYPE abap_bool,

        " Header data
        ls_header_in      TYPE bapisdhd1,
        ls_header_inx     TYPE bapisdhd1x,

        " Partner data
        lt_partners       TYPE TABLE OF bapiparnr,
        ls_partner        TYPE bapiparnr,

        " Item data
        lt_items_in       TYPE TABLE OF bapisditm,
        ls_item_in        TYPE bapisditm,
        lt_items_inx      TYPE TABLE OF bapisditmx,
        ls_item_inx       TYPE bapisditmx,

{{CUSTOM_DATA_DECLARATIONS}}

        " Extension structures for custom fields
        lt_extension_in   TYPE TABLE OF bapiparex,
        ls_extension_in   TYPE bapiparex.

  " Authorization check
  AUTHORITY-CHECK OBJECT 'V_VBAK_VKO'
    ID 'VKORG' FIELD sales_org
    ID 'VTWEG' FIELD dist_channel
    ID 'SPART' FIELD division
    ID 'ACTVT' FIELD '01'.    " Create

  IF sy-subrc <> 0.
    MESSAGE e001(00) WITH 'No authorization for quote creation' RAISING error.
  ENDIF.

  " Validate input parameters
  IF customer_id IS INITIAL.
    MESSAGE e001(00) WITH 'Customer ID is required' RAISING error.
  ENDIF.

  IF valid_until IS INITIAL.
    valid_until = quote_date + 30.  " Default 30 days validity
  ENDIF.

  IF valid_until < quote_date.
    MESSAGE e001(00) WITH 'Valid until date must be after quote date' RAISING error.
  ENDIF.

  " Build header data
  ls_header_in-doc_type   = 'QT'.              " Quote document type
  ls_header_in-sales_org  = sales_org.
  ls_header_in-distr_chan = dist_channel.
  ls_header_in-division   = division.
  ls_header_in-doc_date   = quote_date.
  ls_header_in-valid_from = quote_date.
  ls_header_in-valid_to   = valid_until.
  ls_header_in-purch_no_c = sy-datum.          " Customer PO number (can be customized)

  " Header update indicator
  ls_header_inx-doc_type   = 'X'.
  ls_header_inx-sales_org  = 'X'.
  ls_header_inx-distr_chan = 'X'.
  ls_header_inx-division   = 'X'.
  ls_header_inx-doc_date   = 'X'.
  ls_header_inx-valid_from = 'X'.
  ls_header_inx-valid_to   = 'X'.

  " Build partner data (Sold-to party)
  CLEAR ls_partner.
  ls_partner-partn_role = 'AG'.               " Sold-to party
  ls_partner-partn_numb = customer_id.
  APPEND ls_partner TO lt_partners.

  " Ship-to party (same as sold-to for now)
  CLEAR ls_partner.
  ls_partner-partn_role = 'WE'.               " Ship-to party
  ls_partner-partn_numb = customer_id.
  APPEND ls_partner TO lt_partners.

{{CUSTOM_FIELD_PROCESSING}}

  " Call BAPI to create quote
  CALL FUNCTION 'BAPI_QUOTATION_CREATEFROMDATA2'
    EXPORTING
      quotation_header_in     = ls_header_in
      quotation_header_inx    = ls_header_inx
    IMPORTING
      salesdocument           = lv_quote_number
    TABLES
      return                  = lt_return
      quotation_partners      = lt_partners
      quotation_items_in      = lt_items_in
      quotation_items_inx     = lt_items_inx
      extensionin             = lt_extension_in.

  " Check for errors
  LOOP AT lt_return INTO ls_return WHERE type CA 'EA'.
    lv_error = abap_true.
    EXIT.
  ENDLOOP.

  IF lv_error = abap_true OR lv_quote_number IS INITIAL.
    " Rollback changes
    CALL FUNCTION 'BAPI_TRANSACTION_ROLLBACK'.

    " Return error messages
    messages = lt_return.

    MESSAGE e001(00) WITH 'Quote creation failed - see messages' RAISING error.
  ELSE.
    " Commit changes
    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        wait = 'X'.

    " Return success
    quote_number = lv_quote_number.
    messages = lt_return.

    " Log success (optional)
    MESSAGE s001(00) WITH 'Quote' lv_quote_number 'created successfully'.
  ENDIF.

ENDFUNCTION.
