CLASS zcl_{{CUSTOMER}}_quote_mpc_ext DEFINITION
  PUBLIC
  INHERITING FROM zcl_{{CUSTOMER}}_quote_mpc
  CREATE PUBLIC .

  PUBLIC SECTION.

    METHODS define
        REDEFINITION .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_{{CUSTOMER}}_quote_mpc_ext IMPLEMENTATION.

  METHOD define.
*----------------------------------------------------------------------*
* Model Provider Class Extension for Quote Service
* Customer: {{CUSTOMER}}
* Generated: {{DATE}}
*
* Purpose: Extend the generated model with custom annotations and properties
*----------------------------------------------------------------------*

    " Call super class to get standard definitions
    super->define( ).

    " Get entity reference
    DATA(lo_entity) = model->get_entity_type( iv_entity_name = 'Quote' ).

    IF lo_entity IS BOUND.

      " Get properties
      DATA(lo_property) = lo_entity->get_property( iv_property_name = 'QuoteNumber' ).
      IF lo_property IS BOUND.
        " Make quote number read-only (generated by system)
        lo_property->set_creatable( abap_false ).
        lo_property->set_updatable( abap_false ).
      ENDIF.

      lo_property = lo_entity->get_property( iv_property_name = 'CustomerId' ).
      IF lo_property IS BOUND.
        " Mark as required
        lo_property->set_nullable( abap_false ).
        " Add label
        lo_property->set_label( 'Customer ID' ).
      ENDIF.

      lo_property = lo_entity->get_property( iv_property_name = 'QuoteDate' ).
      IF lo_property IS BOUND.
        lo_property->set_nullable( abap_false ).
        lo_property->set_label( 'Quote Date' ).
      ENDIF.

      lo_property = lo_entity->get_property( iv_property_name = 'ValidUntil' ).
      IF lo_property IS BOUND.
        lo_property->set_nullable( abap_false ).
        lo_property->set_label( 'Valid Until' ).
      ENDIF.

      lo_property = lo_entity->get_property( iv_property_name = 'TotalAmount' ).
      IF lo_property IS BOUND.
        " Make total amount read-only (calculated by system)
        lo_property->set_creatable( abap_false ).
        lo_property->set_updatable( abap_false ).
        lo_property->set_label( 'Total Amount' ).
      ENDIF.

      lo_property = lo_entity->get_property( iv_property_name = 'Status' ).
      IF lo_property IS BOUND.
        " Make status read-only (managed by system)
        lo_property->set_creatable( abap_false ).
        lo_property->set_updatable( abap_false ).
        lo_property->set_label( 'Status' ).
      ENDIF.

{{CUSTOM_PROPERTY_DEFINITIONS}}

      " Set entity as creatable
      lo_entity->set_creatable( abap_true ).

      " Entity is not updatable (quotes are created, not updated)
      lo_entity->set_updatable( abap_false ).

      " Entity is not deletable
      lo_entity->set_deletable( abap_false ).

      " Enable search
      lo_entity->set_searchable( abap_true ).

    ENDIF.

  ENDMETHOD.

ENDCLASS.
